on: push
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: pnpm
              run: npm install pnpm@latest -g
            - name: check working directory and files
              run: |
                echo "Current working directory: ${{ github.workspace }}"
                pwd  # Linux/Mac 显示当前路径
                ls -la  # 列出当前目录下的所有文件
            - name: locate vite-project
              run: cd /home/runner/work/test/test/demo/vite-project
            - name: install dependencies
              run: pnpm install
            - name: build project
              run: pnpm build
              env:
                NODE_ENV: production
            - name: run preview
              run: pnpm preview