on: push
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: pnpm
              run: npm install pnpm@latest -g
            - name: check working directory and files
              run: |
                echo "Current working directory: ${{ github.workspace }}"
                pwd  # Linux/Mac 显示当前路径
                ls -la  # 列出当前目录下的所有文件